# Default values for sonarr
# This is a YAML-formatted file.

# General configuration (passed from umbrella chart)
general:
  ingress_host: k8s-mediaserver.k8s.test
  podDistribution: cluster
  initContainer:
    image: docker.io/ubuntu
    tag: 24.04
    # Set to false if cluster enforces non-root policy
    # Note: When false, init container cannot chown root-owned files
    # fsGroup will handle group ownership automatically
    runAsRoot: true
  puid: 911
  pgid: 1001
  storage:
    customVolume: false
    pvcName: mediaserver-pvc
    accessMode: ""
    pvcStorageClass: ""
    subPaths:
      tv: media/tv
      movies: media/movies
      downloads: downloads
      config: config
    volumes: {}
  ingress:
    ingressClassName: ""
  nodeSelector: {}
  tolerations: []

# Sonarr specific configuration
container:
  image: docker.io/linuxserver/sonarr
  # https://hub.docker.com/r/linuxserver/sonarr/tags
  # https://github.com/linuxserver/docker-sonarr/releases/latest
  tag: 4.0.16
  nodeSelector: {}
  port: 8989
  extraEnv: []

service:
  type: ClusterIP
  port: 8989
  nodePort:
  # Defines an additional LB service, requires cloud provider service or MetalLB
  extraLbService:
    enabled: false
    annotations: {}
    port: 80
    loadBalancerIP:

ingress:
  enabled: true
  annotations: {}
  path: /sonarr
  tls:
    enabled: false
    secretName: ""

resources: {}

volume: {}
# name: pvc-sonarr-config
# storageClassName: longhorn
# annotations:
#   my-annotation/test: my-value
# labels:
#   my-label/test: my-other-value
# accessModes: ReadWriteOnce
# storage: 5Gi
# selector: {}
