# Default values for sabnzbd
# This is a YAML-formatted file.

# General configuration (passed from umbrella chart)
general:
  ingress_host: k8s-mediaserver.k8s.test
  podDistribution: cluster
  initContainer:
    image: docker.io/ubuntu
    tag: 24.04
    # Set to false if cluster enforces non-root policy
    # Note: When false, init container cannot chown root-owned files
    # fsGroup will handle group ownership automatically
    runAsRoot: true
  puid: 911
  pgid: 1001
  storage:
    customVolume: false
    pvcName: mediaserver-pvc
    accessMode: ""
    pvcStorageClass: ""
    subPaths:
      tv: media/tv
      movies: media/movies
      downloads: downloads
      sabnzbd: sabnzbd
      config: config
    volumes: {}
  ingress:
    ingressClassName: ""
  nodeSelector: {}
  tolerations: []

# SABnzbd specific configuration
container:
  image: docker.io/linuxserver/sabnzbd
  # https://hub.docker.com/r/linuxserver/sabnzbd/tags
  # https://github.com/linuxserver/docker-sabnzbd/releases/latest
  tag: 4.5.5
  nodeSelector: {}
  port:
    http: 8080
    https: 9090

service:
  http:
    type: ClusterIP
    port: 8080
    nodePort:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
    extraLBAnnotations: {}
  https:
    type: ClusterIP
    port: 9090
    nodePort:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
    extraLBAnnotations: {}

ingress:
  enabled: true
  annotations: {}
  path: /sabnzbd
  tls:
    enabled: false
    secretName: ""

resources: {}

volume: {}
