apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin
type: application
version: 0.1.10
appVersion: 10.11.5
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg
home: https://jellyfin.org/
sources:
- https://github.com/jellyfin/jellyfin
- https://github.com/95gabor/k8s-mediaserver-charts
keywords:
- jellyfin
- media
- server
- streaming
- open-source
maintainers:
- name: 95gabor
