---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
        app: jellyfin
    spec:
      initContainers:
        - name: fix-permissions
          image: "{{ .Values.general.initContainer.image }}:{{ .Values.general.initContainer.tag }}"
          command:
            - sh
            - '-c'
            - chown -R {{ .Values.general.puid }}:{{ .Values.general.pgid }} /config /movies /tv && chown {{ .Values.general.puid }}:{{ .Values.general.pgid }} /run
          volumeMounts:
            - mountPath: /run
              name: run-tmp
            {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
            {{- else }}
            - name: mediaserver-volume
              mountPath: /config
              subPath: "{{ .Values.general.storage.subPaths.config }}/jellyfin"
            {{- end }}
            - name: mediaserver-volume
              mountPath: /movies
              subPath: "{{ .Values.general.storage.subPaths.movies }}"
            - name: mediaserver-volume
              mountPath: /tv
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            capabilities:
              add:
                - CHOWN
              drop:
                - ALL
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.volume }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        {{- end }}
        - name: tmp
          emptyDir:
            medium: Memory
        - name: run-tmp
          emptyDir:
            medium: Memory
      securityContext:
        fsGroup: {{ .Values.general.pgid }}
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: jellyfin
          envFrom:
            - configMapRef:
                name: jellyfin-config
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            tcpSocket:
              port: {{ .Values.container.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          ports:
            - name: jellyfin-port
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /run
              name: run-tmp
            - name: tmp
              mountPath: /tmp
            {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
            {{- else }}
            - name: mediaserver-volume
              mountPath: /config
              subPath: "{{ .Values.general.storage.subPaths.config }}/jellyfin"
            {{- end }}
            - name: mediaserver-volume
              mountPath: /movies
              subPath: "{{ .Values.general.storage.subPaths.movies }}"
            - name: mediaserver-volume
              mountPath: /tv
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
