---
### DEPLOYMENT
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "sabnzbd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sabnzbd.selectorLabels" . | nindent 8 }}
        app: sabnzbd
    spec:
      initContainers:
        - name: config-sabnzbd
          image: "{{ .Values.general.initContainer.image }}:{{ .Values.general.initContainer.tag }}"
          command: ["/init-sabnzbd/init-sabnzbd.sh"]
          volumeMounts:
            - mountPath: /init-sabnzbd
              name: init-files-sabnzbd
          {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /sabnzbd-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/sabnzbd-config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/sabnzbd"
          {{- end }}
          securityContext:
            {{- if .Values.general.initContainer.runAsRoot }}
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
            {{- else }}
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            {{- end }}
      securityContext:
        fsGroup: {{ .Values.general.pgid }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sabnzbd
          envFrom:
            - configMapRef:
                name: sabnzbd-config
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: "{{ .Values.ingress.path }}/wizard/"
              port: {{ .Values.container.port.http }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 20
          ports:
            - name: sabnzbd-http
              containerPort: {{ .Values.container.port.http }}
              protocol: TCP
            - name: sabnzbd-https
              containerPort: {{ .Values.container.port.https }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/sabnzbd"
          {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.volume }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        {{- end }}
        - name: init-files-sabnzbd
          configMap:
            defaultMode: 493
            name: init-sabnzbd-cm
      {{- with merge .Values.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
