---
{{ if .Values.ingress.enabled }}
### INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.jellyfin_ingress_host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.jellyfin_ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: {{ .Values.service.port }}
{{ end }}

