---
kind: ConfigMap
metadata:
  name: sabnzbd-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
### CONFIGMAP
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
