---
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.container.port.http }}
      protocol: TCP
      name: sabnzbd-http
{{ if eq .Values.service.http.type "NodePort" }}
      nodePort: {{ .Values.service.http.nodePort }}
{{ end }}
  selector:
    app: sabnzbd
