apiVersion: v2
name: plex
description: A Helm chart for Plex Media Server
type: application
version: 0.1.6
appVersion: "1.42.2"
icon: https://simpleicons.org/icons/plex.svg
home: https://www.plex.tv/
sources:
  - https://github.com/plexinc/pms-docker
  - https://github.com/95gabor/k8s-mediaserver-charts
keywords:
  - plex
  - media
  - server
  - streaming
  - video
maintainers:
  - name: 95gabor
