---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}
        app: sonarr
    spec:
      initContainers:
        - name: config-sonarr
          image: "{{ .Values.general.initContainer.image }}:{{ .Values.general.initContainer.tag }}"
          command: ["/init-sonarr/init-sonarr.sh"]
          volumeMounts:
            - mountPath: /init-sonarr
              name: init-files-sonarr
          {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /sonarr-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /sonarr-config
              subPath: "{{ .Values.general.storage.subPaths.config }}/sonarr"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
        - name: fix-permissions
          image: "{{ .Values.general.initContainer.image }}:{{ .Values.general.initContainer.tag }}"
          command:
            - sh
            - '-c'
            - chown -R {{ .Values.general.puid }}:{{ .Values.general.pgid }} /config /downloads /tv && chown {{ .Values.general.puid }}:{{ .Values.general.pgid }} /run
          volumeMounts:
            - mountPath: /run
              name: run-tmp
            {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
            {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/sonarr"
            {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
            - name: mediaserver-volume
              mountPath: "/tv"
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            capabilities:
              add:
                - CHOWN
              drop:
                - ALL
      securityContext:
        fsGroup: {{ .Values.general.pgid }}
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sonarr
          envFrom:
            - configMapRef:
                name: sonarr-config
          env:
            {{- with .Values.container.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: "{{ .Values.ingress.path }}/ping"
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 20
          ports:
            - name: sonarr-port
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /run
              name: run-tmp
            - name: tmp
              mountPath: /tmp
            {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
            {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/sonarr"
            {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
            - name: mediaserver-volume
              mountPath: "/tv"
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.volume }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        {{- end }}
        - name: init-files-sonarr
          configMap:
            defaultMode: 493
            name: init-sonarr-cm
        - name: tmp
          emptyDir:
            medium: Memory
        - name: run-tmp
          emptyDir:
            medium: Memory
      {{- with merge .Values.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
