apiVersion: v2
name: jackett
description: A Helm chart for Jackett
type: application
version: 0.1.8
appVersion: "0.24.372"
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-logo.png
home: https://github.com/Jackett/Jackett
sources:
  - https://github.com/Jackett/Jackett
  - https://github.com/95gabor/k8s-mediaserver-charts
keywords:
  - jackett
  - torrent
  - tracker
  - indexer
  - media
maintainers:
  - name: 95gabor
