---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    {{- include "seerr.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "seerr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "seerr.selectorLabels" . | nindent 8 }}
        app: seerr
    spec:
      containers:
        - name: seerr
          envFrom:
            - configMapRef:
                name: seerr-config
          env:
            {{- with .Values.container.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.container.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 20
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.container.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - name: seerr-port
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /app/config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/app/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/seerr"
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.volume }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        {{- end }}
      {{- with merge .Values.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}

