---
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
{{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}
      name: jackett-port
  selector:
    app: jackett

