---
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.utp.type }}
  ports:
    - port: {{ .Values.service.utp.port }}
      targetPort: {{ .Values.container.port.utp }}
      protocol: TCP
      name: trans-port
{{ if eq .Values.service.utp.type "NodePort" }}
      nodePort: {{ .Values.service.utp.nodePort }}
{{ end }}
  selector:
    app: transmission
