---
### DEPLOYMENT
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transmission.selectorLabels" . | nindent 8 }}
        app: transmission
    spec:
      initContainers:
        - name: config-transmission
          image: "{{ .Values.general.initContainer.image }}:{{ .Values.general.initContainer.tag }}"
          command: ["/init-transmission/init-transmission.sh"]
          volumeMounts:
            - mountPath: /init-transmission
              name: init-files-transmission
          {{ if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /transmission-config
          {{ else }}
            - name: mediaserver-volume
              mountPath: "/transmission-config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/transmission"
          {{ end }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
      securityContext:
        fsGroup: {{ .Values.general.pgid }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: transmission
          envFrom:
            - configMapRef:
                name: transmission-config
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: "{{ .Values.ingress.path }}/"
              port: {{ .Values.container.port.utp }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 20
          ports:
            - name: trans-port
              containerPort: {{ .Values.container.port.utp }}
              protocol: TCP
            - name: trans-peer-tcp
              containerPort: {{ .Values.container.port.peer }}
              protocol: TCP
            - name: trans-peer-udp
              containerPort: {{ .Values.container.port.peer }}
              protocol: UDP
          volumeMounts:
          {{ if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
          {{ else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/transmission"
          {{ end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{ if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{ else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{ end }}
        {{ if .Values.volume }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        {{ end }}
        - name: init-files-transmission
          configMap:
            defaultMode: 493
            name: init-transmission-cm
      {{- with merge .Values.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
