---
{{ if .Values.service.utp.extraLbService.enabled }}
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: transmission-lb
  {{- with .Values.service.utp.extraLbService.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.utp.extraLbService.port | default .Values.service.utp.port }}
      targetPort: {{ .Values.container.port.utp }}
      protocol: TCP
      name: trans-port
  loadBalancerIP: {{ .Values.service.utp.extraLbService.loadBalancerIP }}
  selector:
    app: transmission
{{ end }}
