apiVersion: v2
name: radarr
description: A Helm chart for Radarr
type: application
version: 0.1.8
appVersion: "6.0.4"
icon: https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/256.png
home: https://radarr.video/
sources:
  - https://github.com/Radarr/Radarr
  - https://github.com/95gabor/k8s-mediaserver-charts
keywords:
  - radarr
  - movies
  - tracker
  - media
  - automation
maintainers:
  - name: 95gabor
