# Default values for radarr
# This is a YAML-formatted file.

# General configuration (passed from umbrella chart)
general:
  ingress_host: k8s-mediaserver.k8s.test
  podDistribution: cluster
  initContainer:
    image: docker.io/ubuntu
    tag: 24.04
  puid: 911
  pgid: 1001
  storage:
    customVolume: false
    pvcName: mediaserver-pvc
    accessMode: ""
    pvcStorageClass: ""
    subPaths:
      tv: media/tv
      movies: media/movies
      downloads: downloads
      config: config
    volumes: {}
  ingress:
    ingressClassName: ""
  nodeSelector: {}
  tolerations: []

# Radarr specific configuration
container:
  image: docker.io/linuxserver/radarr
  # https://hub.docker.com/r/linuxserver/radarr/tags
  # https://github.com/linuxserver/docker-radarr/releases/latest
  tag: ""
  nodeSelector: {}
  port: 7878
  extraEnv: []

service:
  type: ClusterIP
  port: 7878
  nodePort:
  # Defines an additional LB service, requires cloud provider service or MetalLB
  extraLbService:
    enabled: false
    annotations: {}
    port: 80
    loadBalancerIP:

ingress:
  enabled: true
  annotations: {}
  path: /radarr
  tls:
    enabled: false
    secretName: ""

resources: {}

volume: {}
