apiVersion: v2
name: seerr
description: A Helm chart for Seerr
type: application
version: 0.1.3
appVersion: "sha-bde322d"
icon: https://raw.githubusercontent.com/seerr-team/seerr/main/public/logo_full.svg
home: https://github.com/seerr-team/seerr
sources:
  - https://github.com/seerr-team/seerr
  - https://github.com/95gabor/k8s-mediaserver-charts
keywords:
  - seerr
  - media
  - request
  - discovery
  - plex
  - jellyfin
maintainers:
  - name: 95gabor
