# Default values for seerr
# This is a YAML-formatted file.

# General configuration (passed from umbrella chart)
general:
  ingress_host: k8s-mediaserver.k8s.test
  podDistribution: cluster
  initContainer:
    image: docker.io/ubuntu
    tag: 24.04
  puid: 1000
  pgid: 1000
  storage:
    customVolume: false
    pvcName: mediaserver-pvc
    accessMode: ""
    pvcStorageClass: ""
    subPaths:
      tv: media/tv
      movies: media/movies
      downloads: downloads
      config: config
    volumes: {}
  ingress:
    ingressClassName: ""
  nodeSelector: {}
  tolerations: []

# Seerr specific configuration
container:
  image: ghcr.io/seerr-team/seerr
  # https://github.com/seerr-team/seerr/releases/latest
  # https://github.com/seerr-team/seerr/pkgs/container/seerr
  tag: sha-bde322d
  nodeSelector: {}
  port: 5055
  extraEnv: []

service:
  type: ClusterIP
  port: 5055
  nodePort:
  # Defines an additional LB service, requires cloud provider service or MetalLB
  extraLbService:
    enabled: false
    annotations: {}
    port: 80
    loadBalancerIP:

ingress:
  enabled: true
  annotations: {}
  path: /seerr
  tls:
    enabled: false
    secretName: ""

resources: {}

volume: {}
