apiVersion: v2
appVersion: 0.10.0
description: A Helm chart for Kubernetes mediaserver (umbrella chart)
name: k8s-mediaserver
type: application
version: 0.10.2
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg
home: https://github.com/95gabor/k8s-mediaserver-charts
sources:
  - https://github.com/95gabor/k8s-mediaserver-charts
keywords:
  - media
  - server
  - plex
  - jellyfin
  - sonarr
  - radarr
  - transmission
  - sabnzbd
  - jackett
  - prowlarr
  - seerr
  - streaming
  - automation
maintainers:
  - name: 95gabor
dependencies:
  - name: sonarr
    version: "0.1.1"
    repository: "file://../sonarr"
    condition: sonarr.enabled
  - name: radarr
    version: "0.1.1"
    repository: "file://../radarr"
    condition: radarr.enabled
  - name: jackett
    version: "0.1.1"
    repository: "file://../jackett"
    condition: jackett.enabled
  - name: prowlarr
    version: "0.1.1"
    repository: "file://../prowlarr"
    condition: prowlarr.enabled
  - name: transmission
    version: "0.1.1"
    repository: "file://../transmission"
    condition: transmission.enabled
  - name: sabnzbd
    version: "0.1.1"
    repository: "file://../sabnzbd"
    condition: sabnzbd.enabled
  - name: plex
    version: "0.1.1"
    repository: "file://../plex"
    condition: plex.enabled
  - name: jellyfin
    version: "0.1.1"
    repository: "file://../jellyfin"
    condition: jellyfin.enabled
  - name: seerr
    version: "0.1.1"
    repository: "file://../seerr"
    condition: seerr.enabled
