---
{{ if .Values.service.extraLbService.enabled }}
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: seerr-lb
  {{- with .Values.service.extraLbService.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "seerr.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.extraLbService.port | default .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: seerr-port
  loadBalancerIP: {{ .Values.service.extraLbService.loadBalancerIP }}
  selector:
    app: seerr
{{ end }}
